export const BADGES = [
  {
    id: "bronze_recruit",
    label: "Recruit",
    emoji: "🥉",
    minLevel: 1,
    maxLevel: 2,
    color: "#cd7f32",
    ring: "#cd7f32",
    description: "Just getting started. Every legend begins here.",
  },
  {
    id: "silver_scout",
    label: "Scout",
    emoji: "🥈",
    minLevel: 3,
    maxLevel: 4,
    color: "#a0aec0",
    ring: "#a0aec0",
    description: "Curiosity is your compass. Keep exploring.",
  },
  {
    id: "gold_scholar",
    label: "Scholar",
    emoji: "🏅",
    minLevel: 5,
    maxLevel: 6,
    color: "#d4a017",
    ring: "#d4a017",
    description: "Knowledge is taking shape. A true student of the craft.",
  },
  {
    id: "amethyst_analyst",
    label: "Analyst",
    emoji: "💜",
    minLevel: 7,
    maxLevel: 8,
    color: "#9b59b6",
    ring: "#9b59b6",
    description: "Sharp eyes, sharper mind. Patterns are your playground.",
  },
  {
    id: "sapphire_sage",
    label: "Sage",
    emoji: "🔷",
    minLevel: 9,
    maxLevel: 10,
    color: "#2980b9",
    ring: "#2980b9",
    description: "Wisdom earned. Strategy mastered.",
  },
  {
    id: "flame_expert",
    label: "Expert",
    emoji: "🔥",
    minLevel: 11,
    maxLevel: 12,
    color: "#e67e22",
    ring: "#e67e22",
    description: "On fire. Others look to you for answers.",
  },
  {
    id: "lightning_virtuoso",
    label: "Virtuoso",
    emoji: "⚡",
    minLevel: 13,
    maxLevel: 14,
    color: "#f1c40f",
    ring: "#f1c40f",
    description: "Speed and precision. A virtuoso in every sense.",
  },
  {
    id: "emerald_champion",
    label: "Champion",
    emoji: "🏆",
    minLevel: 15,
    maxLevel: 16,
    color: "#27ae60",
    ring: "#27ae60",
    description: "Champion-tier. You have conquered what most abandon.",
  },
  {
    id: "crimson_elite",
    label: "Elite",
    emoji: "✨",
    minLevel: 17,
    maxLevel: 18,
    color: "#e74c3c",
    ring: "#e74c3c",
    description: "Elite. Rare. The top tier calls your name.",
  },
  {
    id: "cosmic_luminary",
    label: "Luminary",
    emoji: "🌌",
    minLevel: 19,
    maxLevel: 19,
    color: "#8e44ad",
    ring: "#8e44ad",
    description: "A light in the dark. Others follow your glow.",
  },
  {
    id: "star_shepard",
    label: "Shepard",
    emoji: "🌟",
    minLevel: 20,
    maxLevel: 20,
    color: "#f39c12",
    ring: "#FFD700",
    description: "The pinnacle. You are the Shepard. 🌟",
  },
];

export function getBadgeForLevel(level) {
  return BADGES.find((b) => level >= b.minLevel && level <= b.maxLevel) ?? BADGES[0];
}

export function getUnlockedBadges(currentLevel) {
  return BADGES.filter((b) => currentLevel >= b.minLevel);
}